### ISSUE TITLE
addResponseKeyboard doesn't show a keyboard

### ISSUE THREAD

**Issue by pukhalski** [kikinteractive/kik-node#19]
### Expected behavior
Show suggestions

### Actual behavior
Standard user keyboard is shown.

### Enviroment Details
Bot is not published to the store but available for testing. Tried via http API and via this library — end result remains the same. I'm not using it as a reply to the message, but as a new text message with a keyboard added. Could it be the problem? Tried to create another bot but it didn't help.

kik-node 2.0.8

### Steps to reproduce the behaviour

Not sure whether it could be reproducible at all.

**Comment by sgaurav** [comment]
I can confirm this problem. Unable to show a custom options.

**Comment by phips28** [comment]
@pukhalski can you provide a codesnippet?
My keyboards are all fine!

**Comment by pukhalski** [comment]
```javascript
    let msg = Bot.Message.text('Work-work!!!').addResponseKeyboard(['Yes, please, add it', 'Another answer'])
    return bot.send(msg, 'pukhalski').then(res => {
      console.log(res, JSON.stringify(msg))
    }).catch(err => console.log(err));
```

@phips28, here it goes. Nothing special. I see the text message but no suggested answer options so far...

**Comment by pukhalski** [comment]
Also I was trying to do this using HTTP API, the result remains the same — text message with no options.

**Comment by pukhalski** [comment]
Any updates so far?

**Comment by phips28** [comment]
This is my send method:
`
_bot.send(Bot.Message.text(text)
        .addTextResponse(constant.BOT.MESSAGE.START_VOTING)
        .addTextResponse(constant.BOT.MESSAGE.CHOOSE_CATEGORY)
        .addTextResponse(constant.BOT.MESSAGE.TRENDING_HASHTAGS)
        .addResponseKeyboard(Bot.Response.friendPicker(constant.BOT.MESSAGE.INVITE_FRIENDS))
        ,
        chatBotUserSession.chatBotUserId, chatBotUserSession.chatId);
`
IMO adding the text responses like this is more "readable" and you can change the order quickly.
(See also FriendPicker -> there is no direct message like addFriendPickerResponse() so far.)

**Comment by pukhalski** [comment]
The thing is that I am using API directly. I was trying through this lib just for the sake of testing as well as I don't know where to communicate Kik tech support :/

Thanks, @phips28, I'll try it out as well.

**Comment by pukhalski** [comment]
Same result with the approach of restructuring into a set of separate text responses, as you've shown above, @phips28. Thank you anyway 👍

**Comment by remvst** [comment]
@pukhalski @phips28 are you guys still experiencing problems with the keyboards? If not I will close this issue.
This snippet should work:
```javascript
const msg = Bot.Message.text('foo');
msg.addResponseKeyboard(['bar', 'baz']);
bot.send(msg, 'yourusername');
```

**Comment by pukhalski** [comment]
Please, close. @remvst 

But I need to let you know, that the issue was on API side, not yours. Thanks.
