### ISSUE TITLE
Is there a way to add middleware to the kik-node project?

### ISSUE THREAD

**Issue by arunthampi** [kikinteractive/kik-node#23]
We're building an analytics + engagement platform for Kik bots at [Botmetrics](https://getbotmetrics.com) and would love to add a middleware layer that users can enable to get analytics for free.

**Comment by remvst** [comment]
@arunthampi You could do something like that:
```javascript
bot.use((msg, next) => {
    send_analytics();
    next(); // keep processing
});
```
You'll just need to place that before any other handler (like `use()`, `onTextMessage()`...).

Hope that helps

**Comment by arunthampi** [comment]
@remvst cool thanks!
