### ISSUE TITLE
Is there a way for middleware to be called when messages are sent to?

### ISSUE THREAD

**Issue by arunthampi** [kikinteractive/kik-node#24]
In `API.sendMessages` perhaps? This is important for us to track both incoming and outgoing messages in our analytics stack (with very little work required from the user)

**Comment by phips28** [comment]
@arunthampi I wrote an article about "track outgoing http(s) requests":
https://chatbotsmagazine.com/track-outgoing-http-s-requests-in-nodejs-48608553f03c#.rh623uyg1

Incoming is easy because you have just one endpoint for it.

**Comment by arunthampi** [comment]
@phips28 yup wanted to find out if there was a more "official" way than monkey-patching :)

**Comment by phips28** [comment]
afaik, there is no hook support by kik-node.

**Comment by remvst** [comment]
@phips28 @arunthampi this is a little sketchy indeed. I'll see if I can come up with a better supported way, but feel free to submit a PR if you have an idea ;)

**Comment by remvst** [comment]
https://github.com/kikinteractive/kik-node/pull/25 just went out, so I'm assuming this is solved

**Comment by arunthampi** [comment]
awesome! 🙌 💫
