### ISSUE TITLE
Sending Gif to KiK chat Bot 

### ISSUE THREAD

**Issue by VishalWaman** [kikinteractive/kik-node#52]
We have been trying to send GIF to KiK chat bot.

We have sent video message with GIF link and Autoplay + Loop set to true

But this dont work if user has set to not auto download Videos..

Can you suggest help on this.

**Comment by VishalWaman** [comment]
@whited @bnmrrs @oryband @jairajs89 @gadisr  any help on this ?
Can we send GIF to kik and basically it should autoplay irrespective on KiK App's Autoplay settings

We have tried sending GIF as Video message It p;ays but when we Set AutoPlay= "False" video is not auto played.. 

Does KiK support GIF ??

**Comment by davidbistolas** [comment]
Yes. We support gif as video. Send me the gif and your JSON request please.

**Comment by VishalWaman** [comment]
@davidbistolas we are able to get GIF on platform.. 
But as its rendered as a video.. 
If user has set "Auto Play Video" in Setting > Chat Setting > Auto Play Videos set to "False".. 
Its not auto played..

URL : https://api.kik.com/v1/message
Body : 
`{
    "messages": [
        {
            "chatId": "796882f9e2f99c625f2b20f78026391149b1a4a5b7766a1d280fbe8523cd9325",
            "type": "video",
            "to": "vishalwaman",
            "videoUrl": "http://i.giphy.com/Ki55RUbOV5njy.gif",
            "muted": true,
            "autoplay": true,
            "attribution": "camera"
        }
    ]
}`

**Comment by davidbistolas** [comment]
That's correct. Gifs are rendered as video. Specifically, h264 encoded MP4.  

Also correct: The client's autoplay settings override the video message's autoplay settings. This is the  expected behaviour.

**Comment by VishalWaman** [comment]
@davidbistolas  Is there any way to send GIF without Video type message..

Or Play GIF having "Setting > Chat Setting > Auto Play Videos set to "False"..

Just to confirm

**Comment by davidbistolas** [comment]
No. It must be sent as a video message. 

~ David
